const FINANCIAL_DASHBOARD = 'FINANCIAL_DASHBOARD';
const FINANCIAL_CONFIG_COA = 'FINANCIAL_CONFIG_COA';
const FINANCIAL_CONFIG_VT = 'FINANCIAL_CONFIG_VT';

export { FINANCIAL_CONFIG_COA, FINANCIAL_CONFIG_VT, FINANCIAL_DASHBOARD };
